runtime: python311
entrypoint: gunicorn -b :$PORT main_appengine:app

endpoints_api_service:
# !!! ВАЖНО !!! Введите URL своего endpoint
# Данная команда подключает ESPv2 (Extensible Service Provider v2) для мониторинга Endpoints
  name: [PROJECT_ID].appspot.com
  rollout_strategy: managed
